Tentative changes to implement new building process and package configuration.  o no longer creates CPP_OPTIONS.h (#def's now in PACKAGES.h)  o uses -DALLOW_* on cmd-line Todo:  o lots

diff --git a/tools/genmake2 b/tools/genmake2
--- a/tools/genmake2
+++ b/tools/genmake2
@@ -1,12 +1,43 @@
 #!/bin/bash
 #
-# $Header: /u/gcmpack/MITgcm/tools/genmake2,v 1.11 2003/09/29 16:15:23 edhill Exp $
+# $Header: /u/gcmpack/MITgcm/tools/genmake2,v 1.11.2.1 2003/10/01 18:44:48 adcroft Exp $
 #
 # Makefile generator for MITgcm UV codes
 #   created  by cnh 03/98
 #   adapted  by aja 06/98
 #   modified by aja 01/00
 #   rewritten in bash by eh3 08/03
+
+# Search for particular CPP #cmds associated with packages
+# usage: test_for_package_in_cpp_options CPP_file package_name
+test_for_package_in_cpp_options() {
+   cpp_options=$1
+   pkg=$2
+   grep -i "#define.*ALLOW_$pkg" $cpp_options > /dev/null 2>&1
+   RETVAL=$?
+   if test "x${RETVAL}" = x0 ; then
+      echo "Error: In $cpp_options there is an illegal line: #define ALLOW_$pkg"
+      exit 99
+   fi
+   grep -i "#undef.*ALLOW_$pkg" $cpp_options > /dev/null 2>&1
+   RETVAL=$?
+   if test "x${RETVAL}" = x0 ; then
+      echo "Error: In $cpp_options there is an illegal line: #undef ALLOW_$pkg"
+      exit 99
+   fi
+   grep -i "#define.*DISABLE_$pkg" $cpp_options > /dev/null 2>&1
+   RETVAL=$?
+   if test "x${RETVAL}" = x0 ; then
+      echo "Error: In $cpp_options there is an illegal line: #define DISABLE_$pkg"
+      exit 99
+   fi
+   grep -i "#undef.*DISABLE_$pkg" $cpp_options > /dev/null 2>&1
+   RETVAL=$?
+   if test "x${RETVAL}" = x0 ; then
+      echo "Error: In $cpp_options there is an illegal line: #undef DISABLE_$pkg"
+      exit 99
+   fi
+}
 
 
 # Guess possible config options for this host
@@ -645,7 +676,7 @@ for p in $PACKAGES ; do
 done
 PACKAGES="$pack"
 echo "  applying ENABLE settings"
-rm -f ./.tmp_pack
+echo "" > ./.tmp_pack
 PACKAGES="$PACKAGES $ENABLE"
 for i in $PACKAGES ; do
     if test ! -d "$ROOTDIR/pkg/$i" ; then
@@ -761,34 +792,17 @@ done
 # done
 # echo
 
-echo "  Searching for CPP_OPTIONS.h (macros and flags for configuring the model):"
-CPP_OPTIONS=
-spaths=". $SOURCEDIRS"
-for i in $spaths ; do
-    try="$i/CPP_OPTIONS.h"
-    #  echo -n "    trying $try : "
-    if test -f $try -a -r $try ; then
-	echo "    found CPP_OPTIONS=\"$try\""
-	CPP_OPTIONS="$try"
-	if test "x$i" != "x." ; then
-	    cp -f $CPP_OPTIONS .
-	fi
-	break
+# Create a list of #define and #undef to enable/disable packages
+PACKAGES_DOT_H=PACKAGES.h
+if test -e $PACKAGES_DOT_H ; then
+    if test ! -e $PACKAGES_DOT_H.bak ; then
+	cp -f $PACKAGES_DOT_H $PACKAGES_DOT_H.bak
     fi
-done
-if test "x$CPP_OPTIONS" = x ; then
-    echo "Error: can't find \"CPP_OPTIONS.h\" in the path list: $spaths"
-    exit 1
-fi
-if test -e CPP_OPTIONS.h ; then
-    if test ! -e CPP_OPTIONS.h.bak ; then
-	cp -f CPP_OPTIONS.h CPP_OPTIONS.h.bak
-    fi
-    cat CPP_OPTIONS.h \
+    cat $PACKAGES_DOT_H \
 	| awk 'BEGIN{p=1;} ($1=="C===" && $2=="GENMAKE"){p=0;} {if (p==1) print $0}' \
-	> CPP_OPTIONS.h.tmp
+	> $PACKAGES_DOT_H.tmp
 fi
-cat <<EOF >>CPP_OPTIONS.h.tmp
+cat <<EOF >>$PACKAGES_DOT_H.tmp
 C=== GENMAKE v2 ===
 C  The following defines have been set by GENMAKE, so please do not
 C  edit anything below these comments.  In general, you should
@@ -814,7 +828,8 @@ for n in $names ; do
 	done
 	if test "x$has_pack" = xf ; then
 	    undef=`echo "ALLOW_$n" | awk '{print toupper($0)}'`
-	    echo "#undef $undef" >> CPP_OPTIONS.h.tmp
+	    echo "#undef $undef" >> $PACKAGES_DOT_H.tmp
+#           DEFINES="$DEFINES -U$undef"
 
 #EH3  WARNING :  This is an UGLY HACK that needs to be removed!!!
 	    case $n in 
@@ -823,9 +838,6 @@ for n in $names ; do
 		    ;;
 		mom_vecinv)
 		    DEFINES="$DEFINES -DDISABLE_MOM_VECINV"
-		    ;;
-		generic_advdiff)
-		    DEFINES="$DEFINES -DDISABLE_GENERIC_ADVDIFF"
 		    ;;
 		debug)
 		    DEFINES="$DEFINES -DDISABLE_DEBUGMODE"
@@ -836,24 +848,27 @@ for n in $names ; do
 	fi
     fi
 done
-cat <<EOF >>CPP_OPTIONS.h.tmp
+cat <<EOF >>$PACKAGES_DOT_H.tmp
 
 C  Packages enabled by genmake:
 EOF
 for i in $PACKAGES ; do
     def=`echo "ALLOW_$i" | awk '{print toupper($0)}'`
-    echo "#define $def" >> CPP_OPTIONS.h.tmp
+    echo "#define $def" >> $PACKAGES_DOT_H.tmp
+    DEFINES="$DEFINES -D$def"
 
 #EH3  WARNING :  This is an UGLY HACK that needs to be removed!!!
     case $i in 
 	aim_v23)
-	    echo "#define   ALLOW_AIM" >> CPP_OPTIONS.h.tmp
+	    echo "#define   ALLOW_AIM" >> $PACKAGES_DOT_H.tmp
+            DEFINES="$DEFINES -DALLOW_AIM"
+	    echo "Warning: ALLOW_AIM is set to enable aim_v23. This is REALLY ugly Jean-Michel :-)"
 	    ;;
     esac
 #EH3  WARNING :  This is an UGLY HACK that needs to be removed!!!
 
 done
-mv -f CPP_OPTIONS.h.tmp CPP_OPTIONS.h
+mv -f $PACKAGES_DOT_H.tmp $PACKAGES_DOT_H
 
 echo "  Adding STANDARDDIRS"
 BUILDDIR=${BUILDDIR:-.}
@@ -877,14 +892,39 @@ for d in $STANDARDDIRS ; do
     fi
 done
 
+echo "  Searching for CPP_OPTIONS.h (macros and flags for configuring the model):"
+CPP_OPTIONS=
+spaths=". $INCLUDEDIRS"
+for i in $spaths ; do
+    try="$i/CPP_OPTIONS.h"
+    #  echo -n "    trying $try : "
+    if test -f $try -a -r $try ; then
+	echo "    found CPP_OPTIONS=\"$try\""
+	CPP_OPTIONS="$try"
+#aja	if test "x$i" != "x." ; then
+#aja	    cp -f $CPP_OPTIONS .
+#aja	fi
+	break
+    fi
+done
+if test "x$CPP_OPTIONS" = x ; then
+    echo "Error: can't find \"CPP_OPTIONS.h\" in the path list: $spaths"
+    exit 1
+fi
+# New safety test: make sure packages are not mentioned in CPP_OPTIONS.h
+names=`ls -1 "$ROOTDIR/pkg"`
+for n in $names ; do
+    test_for_package_in_cpp_options $CPP_OPTIONS $n
+done
+
 
 echo
 echo "===  Creating the Makefile  ==="
 echo "  setting INCLUDES"
 for i in $INCLUDEDIRS ; do
-    if test -d $i ; then
-	INCLUDES="$INCLUDES -I$i"
-    else
+    if ! test -d $i ; then
+#	INCLUDES="$INCLUDES -I$i"
+#   else
 	echo "Warning: can't find INCLUDEDIRS=\"$i\""
     fi
 done
@@ -942,6 +982,8 @@ echo "" >> srclist.inc
 echo "" >> csrclist.inc
 echo "" >> f90srclist.inc
 echo "" >> hlist.inc
+
+echo $DEFINES
 
 if test -e $MAKEFILE ; then
     mv -f $MAKEFILE "$MAKEFILE.bak"
@@ -1064,13 +1106,13 @@ clean:
 Clean:
 	@make clean
 	@make cleanlinks
-	-rm -f Makefile.bak
+	-rm -f Makefile.bak gm_state gm_optfile make.log PACKAGES.h*
 CLEAN:
 	@make Clean
 	-find \$(EXEDIR) -name "*.meta" -exec rm {} \;
 	-find \$(EXEDIR) -name "*.data" -exec rm {} \;
 	-find \$(EXEDIR) -name "fort.*" -exec rm {} \;
-	-rm -f \$(EXECUTABLE)
+	-rm -f \$(EXECUTABLE) output.txt
 
 makefile:
 	${0} $@
